server:
  port: 9000

spring:
  application:
    name: spring-security-client
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true